version: "3.9"

services:
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
